[package]
authors = ["Kenan Sulayman <kenan@sly.mn>"]
name = "anonium"
version = "0.1.0"

[dependencies]
lazy_static = "1.0.0"
rand = "0.4.1"
redis = "0.8.0"
rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = "0.3.5"
time = "0.1.38"
